INSERT INTO article (title, content, hashtag, created_at, created_by, modified_at, modified_by)
VALUES
    ('Title 1', 'This is content for article 1', '#hashtag1', NOW(), 'user1', NOW(), 'user1'),
    ('Title 2', 'This is content for article 2', '#hashtag2', NOW(), 'user2', NOW(), 'user2'),
    ('Title 3', 'This is content for article 3', '#hashtag3', NOW(), 'user3', NOW(), 'user3'),
    ('Title 4', 'This is content for article 4', '#hashtag4', NOW(), 'user4', NOW(), 'user4'),
    ('Title 5', 'This is content for article 5', '#hashtag5', NOW(), 'user5', NOW(), 'user5'),
    ('Title 6', 'This is content for article 6', '#hashtag6', NOW(), 'user6', NOW(), 'user6'),
    ('Title 7', 'This is content for article 7', '#hashtag7', NOW(), 'user7', NOW(), 'user7'),
    ('Title 8', 'This is content for article 8', '#hashtag8', NOW(), 'user8', NOW(), 'user8'),
    ('Title 9', 'This is content for article 9', '#hashtag9', NOW(), 'user9', NOW(), 'user9'),
    ('Title 10', 'This is content for article 10', '#hashtag10', NOW(), 'user10', NOW(), 'user10'),
    ('Title 11', 'This is content for article 11', '#hashtag11', NOW(), 'user11', NOW(), 'user11'),
    ('Title 12', 'This is content for article 12', '#hashtag12', NOW(), 'user12', NOW(), 'user12'),
    ('Title 13', 'This is content for article 13', '#hashtag13', NOW(), 'user13', NOW(), 'user13'),
    ('Title 14', 'This is content for article 14', '#hashtag14', NOW(), 'user14', NOW(), 'user14'),
    ('Title 15', 'This is content for article 15', '#hashtag15', NOW(), 'user15', NOW(), 'user15'),
    ('Title 16', 'This is content for article 16', '#hashtag16', NOW(), 'user16', NOW(), 'user16'),
    ('Title 17', 'This is content for article 17', '#hashtag17', NOW(), 'user17', NOW(), 'user17'),
    ('Title 18', 'This is content for article 18', '#hashtag18', NOW(), 'user18', NOW(), 'user18'),
    ('Title 19', 'This is content for article 19', '#hashtag19', NOW(), 'user19', NOW(), 'user19'),
    ('Title 20', 'This is content for article 20', '#hashtag20', NOW(), 'user20', NOW(), 'user20'),
    ('Title 21', 'This is content for article 21', '#hashtag21', NOW(), 'user21', NOW(), 'user21'),
    ('Title 22', 'This is content for article 22', '#hashtag22', NOW(), 'user22', NOW(), 'user22'),
    ('Title 23', 'This is content for article 23', '#hashtag23', NOW(), 'user23', NOW(), 'user23'),
    ('Title 24', 'This is content for article 24', '#hashtag24', NOW(), 'user24', NOW(), 'user24'),
    ('Title 25', 'This is content for article 25', '#hashtag25', NOW(), 'user25', NOW(), 'user25'),
    ('Title 26', 'This is content for article 26', '#hashtag26', NOW(), 'user26', NOW(), 'user26'),
    ('Title 27', 'This is content for article 27', '#hashtag27', NOW(), 'user27', NOW(), 'user27'),
    ('Title 28', 'This is content for article 28', '#hashtag28', NOW(), 'user28', NOW(), 'user28'),
    ('Title 29', 'This is content for article 29', '#hashtag29', NOW(), 'user29', NOW(), 'user29'),
    ('Title 30', 'This is content for article 30', '#hashtag30', NOW(), 'user30', NOW(), 'user30'),
    ('Title 31', 'This is content for article 31', '#hashtag31', NOW(), 'user31', NOW(), 'user31'),
    ('Title 32', 'This is content for article 32', '#hashtag32', NOW(), 'user32', NOW(), 'user32'),
    ('Title 33', 'This is content for article 33', '#hashtag33', NOW(), 'user33', NOW(), 'user33'),
    ('Title 34', 'This is content for article 34', '#hashtag34', NOW(), 'user34', NOW(), 'user34'),
    ('Title 35', 'This is content for article 35', '#hashtag35', NOW(), 'user35', NOW(), 'user35'),
    ('Title 36', 'This is content for article 36', '#hashtag36', NOW(), 'user36', NOW(), 'user36'),
    ('Title 37', 'This is content for article 37', '#hashtag37', NOW(), 'user37', NOW(), 'user37'),
    ('Title 38', 'This is content for article 38', '#hashtag38', NOW(), 'user38', NOW(), 'user38'),
    ('Title 39', 'This is content for article 39', '#hashtag39', NOW(), 'user39', NOW(), 'user39'),
    ('Title 40', 'This is content for article 40', '#hashtag40', NOW(), 'user40', NOW(), 'user40'),
    ('Title 41', 'This is content for article 41', '#hashtag41', NOW(), 'user41', NOW(), 'user41'),
    ('Title 42', 'This is content for article 42', '#hashtag42', NOW(), 'user42', NOW(), 'user42'),
    ('Title 43', 'This is content for article 43', '#hashtag43', NOW(), 'user43', NOW(), 'user43'),
    ('Title 44', 'This is content for article 44', '#hashtag44', NOW(), 'user44', NOW(), 'user44'),
    ('Title 45', 'This is content for article 45', '#hashtag45', NOW(), 'user45', NOW(), 'user45'),
    ('Title 46', 'This is content for article 46', '#hashtag46', NOW(), 'user46', NOW(), 'user46'),
    ('Title 47', 'This is content for article 47', '#hashtag47', NOW(), 'user47', NOW(), 'user47'),
    ('Title 48', 'This is content for article 48', '#hashtag48', NOW(), 'user48', NOW(), 'user48'),
    ('Title 49', 'This is content for article 49', '#hashtag49', NOW(), 'user49', NOW(), 'user49'),
    ('Title 50', 'This is content for article 50', '#hashtag50', NOW(), 'user50', NOW(), 'user50'),
    ('Title 51', 'This is content for article 51', '#hashtag51', NOW(), 'user51', NOW(), 'user51'),
    ('Title 52', 'This is content for article 52', '#hashtag52', NOW(), 'user52', NOW(), 'user52'),
    ('Title 53', 'This is content for article 53', '#hashtag53', NOW(), 'user53', NOW(), 'user53'),
    ('Title 54', 'This is content for article 54', '#hashtag54', NOW(), 'user54', NOW(), 'user54'),
    ('Title 55', 'This is content for article 55', '#hashtag55', NOW(), 'user55', NOW(), 'user55'),
    ('Title 56', 'This is content for article 56', '#hashtag56', NOW(), 'user56', NOW(), 'user56'),
    ('Title 57', 'This is content for article 57', '#hashtag57', NOW(), 'user57', NOW(), 'user57'),
    ('Title 58', 'This is content for article 58', '#hashtag58', NOW(), 'user58', NOW(), 'user58'),
    ('Title 59', 'This is content for article 59', '#hashtag59', NOW(), 'user59', NOW(), 'user59'),
    ('Title 60', 'This is content for article 60', '#hashtag60', NOW(), 'user60', NOW(), 'user60'),
    ('Title 61', 'This is content for article 61', '#hashtag61', NOW(), 'user61', NOW(), 'user61'),
    ('Title 62', 'This is content for article 62', '#hashtag62', NOW(), 'user62', NOW(), 'user62'),
    ('Title 63', 'This is content for article 63', '#hashtag63', NOW(), 'user63', NOW(), 'user63'),
    ('Title 64', 'This is content for article 64', '#hashtag64', NOW(), 'user64', NOW(), 'user64'),
    ('Title 65', 'This is content for article 65', '#hashtag65', NOW(), 'user65', NOW(), 'user65'),
    ('Title 66', 'This is content for article 66', '#hashtag66', NOW(), 'user66', NOW(), 'user66'),
    ('Title 67', 'This is content for article 67', '#hashtag67', NOW(), 'user67', NOW(), 'user67'),
    ('Title 68', 'This is content for article 68', '#hashtag68', NOW(), 'user68', NOW(), 'user68'),
    ('Title 69', 'This is content for article 69', '#hashtag69', NOW(), 'user69', NOW(), 'user69'),
    ('Title 70', 'This is content for article 70', '#hashtag70', NOW(), 'user70', NOW(), 'user70'),
    ('Title 71', 'This is content for article 71', '#hashtag71', NOW(), 'user71', NOW(), 'user71'),
    ('Title 72', 'This is content for article 72', '#hashtag72', NOW(), 'user72', NOW(), 'user72'),
    ('Title 73', 'This is content for article 73', '#hashtag73', NOW(), 'user73', NOW(), 'user73'),
    ('Title 74', 'This is content for article 74', '#hashtag74', NOW(), 'user74', NOW(), 'user74'),
    ('Title 75', 'This is content for article 75', '#hashtag75', NOW(), 'user75', NOW(), 'user75'),
    ('Title 76', 'This is content for article 76', '#hashtag76', NOW(), 'user76', NOW(), 'user76'),
    ('Title 77', 'This is content for article 77', '#hashtag77', NOW(), 'user77', NOW(), 'user77'),
    ('Title 78', 'This is content for article 78', '#hashtag78', NOW(), 'user78', NOW(), 'user78'),
    ('Title 79', 'This is content for article 79', '#hashtag79', NOW(), 'user79', NOW(), 'user79'),
    ('Title 80', 'This is content for article 80', '#hashtag80', NOW(), 'user80', NOW(), 'user80'),
    ('Title 81', 'This is content for article 81', '#hashtag81', NOW(), 'user81', NOW(), 'user81'),
    ('Title 82', 'This is content for article 82', '#hashtag82', NOW(), 'user82', NOW(), 'user82'),
    ('Title 83', 'This is content for article 83', '#hashtag83', NOW(), 'user83', NOW(), 'user83'),
    ('Title 84', 'This is content for article 84', '#hashtag84', NOW(), 'user84', NOW(), 'user84'),
    ('Title 85', 'This is content for article 85', '#hashtag85', NOW(), 'user85', NOW(), 'user85'),
    ('Title 86', 'This is content for article 86', '#hashtag86', NOW(), 'user86', NOW(), 'user86'),
    ('Title 87', 'This is content for article 87', '#hashtag87', NOW(), 'user87', NOW(), 'user87'),
    ('Title 88', 'This is content for article 88', '#hashtag88', NOW(), 'user88', NOW(), 'user88'),
    ('Title 89', 'This is content for article 89', '#hashtag89', NOW(), 'user89', NOW(), 'user89'),
    ('Title 90', 'This is content for article 90', '#hashtag90', NOW(), 'user90', NOW(), 'user90'),
    ('Title 91', 'This is content for article 91', '#hashtag91', NOW(), 'user91', NOW(), 'user91'),
    ('Title 92', 'This is content for article 92', '#hashtag92', NOW(), 'user92', NOW(), 'user92'),
    ('Title 93', 'This is content for article 93', '#hashtag93', NOW(), 'user93', NOW(), 'user93'),
    ('Title 94', 'This is content for article 94', '#hashtag94', NOW(), 'user94', NOW(), 'user94'),
    ('Title 95', 'This is content for article 95', '#hashtag95', NOW(), 'user95', NOW(), 'user95'),
    ('Title 96', 'This is content for article 96', '#hashtag96', NOW(), 'user96', NOW(), 'user96'),
    ('Title 97', 'This is content for article 97', '#hashtag97', NOW(), 'user97', NOW(), 'user97'),
    ('Title 98', 'This is content for article 98', '#hashtag98', NOW(), 'user98', NOW(), 'user98'),
    ('Title 99', 'This is content for article 99', '#hashtag99', NOW(), 'user99', NOW(), 'user99'),
    ('Title 100', 'This is content for article 100', '#hashtag100', NOW(), 'user100', NOW(), 'user100');


-- ArticleComment 데이터 생성 (댓글 데이터 예시)
INSERT INTO article_comment (id, article_id, content, created_at, created_by, modified_at, modified_by)
VALUES
    (1, 1, 'This is a comment on article 1', NOW(), 'user1', NOW(), 'user1'),
    (2, 1, 'Another comment on article 1', NOW(), 'user2', NOW(), 'user2'),
    (3, 2, 'This is a comment on article 2', NOW(), 'user3', NOW(), 'user3'),
    (4, 2, 'Another comment on article 2', NOW(), 'user4', NOW(), 'user4'),
    (5, 3, 'This is a comment on article 3', NOW(), 'user5', NOW(), 'user5'),
    (6, 3, 'Another comment on article 3', NOW(), 'user6', NOW(), 'user6'),
    (7, 1, 'Yet another comment on article 1', NOW(), 'user7', NOW(), 'user7'),
    (8, 2, 'Interesting comment on article 2', NOW(), 'user8', NOW(), 'user8'),
    (9, 3, 'Nice thoughts on article 3', NOW(), 'user9', NOW(), 'user9'),
    (10, 1, 'Insightful comment on article 1', NOW(), 'user10', NOW(), 'user10'),
    (11, 1, 'Comment 11 on article 1', NOW(), 'user11', NOW(), 'user11'),
    (12, 2, 'Comment 12 on article 2', NOW(), 'user12', NOW(), 'user12'),
    (13, 3, 'Comment 13 on article 3', NOW(), 'user13', NOW(), 'user13'),
    (14, 1, 'Comment 14 on article 1', NOW(), 'user14', NOW(), 'user14'),
    (15, 2, 'Comment 15 on article 2', NOW(), 'user15', NOW(), 'user15'),
    (16, 3, 'Comment 16 on article 3', NOW(), 'user16', NOW(), 'user16'),
    (17, 1, 'Comment 17 on article 1', NOW(), 'user17', NOW(), 'user17'),
    (18, 2, 'Comment 18 on article 2', NOW(), 'user18', NOW(), 'user18'),
    (19, 3, 'Comment 19 on article 3', NOW(), 'user19', NOW(), 'user19'),
    (20, 1, 'Comment 20 on article 1', NOW(), 'user20', NOW(), 'user20');